<?php
/**
 * Theme functions and definitions.
 * This child theme was generated by Merlin WP.
 *
 * @link https://developer.wordpress.org/themes/basics/theme-functions/
 */

/*
 * If your child theme has more than one .css file (eg. ie.css, style.css, main.css) then
 * you will have to make sure to maintain all of the parent theme dependencies.
 *
 * Make sure you're using the correct handle for loading the parent theme's styles.
 * Failure to use the proper tag will result in a CSS file needlessly being loaded twice.
 * This will usually not affect the site appearance, but it's inefficient and extends your page's loading time.
 *
 * @link https://codex.wordpress.org/Child_Themes
 */
function vinero_child_enqueue_styles() {
    wp_enqueue_style( 'vinero-style' , get_template_directory_uri() . '/style.css' );
    wp_enqueue_style( 'vinero-child-style',
        get_stylesheet_directory_uri() . '/style.css',
        array( 'vinero-style' ),
        wp_get_theme()->get('Version')
    );
}

add_action(  'wp_enqueue_scripts', 'vinero_child_enqueue_styles' );

# Import ACF

if ( ! VINERO_DEVELOPMENT ) {
	add_filter( 'acf/settings/show_admin', '__return_true' );
}

add_action('acf/init', 'my_acf_init');
function my_acf_init() {
    acf_update_setting('show_admin', true);
}
